### ISSUE TITLE
Question: Convert a seq[CigarElement] to Cigar

### ISSUE THREAD

**Issue by andreas-wilm** [brentp/hts-nim-tools#9]
Hi Brent,

First of all, thanks for hts-nim!

I'm writing a realigner using hts-nim. For the realignment I have a seq[CigarElement] but am struggling to convert that to Cigar. newCigar() takes a ptr uint32, so I don't know how to go about this. It would be great to see examples of how to create Cigars from scratch. Ultimately I would like to replace a Cigar in a given read with this new Cigar. Any chance you would have some example code for that scenario as well? 

Many thanks,
Andreas

**Comment by andreas-wilm** [comment]
Just found your [bamject](https://github.com/brentp/bamject). So I guess I have to convert the read to string first and do the modifications there 😮

**Comment by brentp** [comment]
Hi Andreas, I just pushed a change to hts-nim that allows you to create a Cigar from a `seq[CigarElement]` 

Check the test and docstring as you are responsible for ensuruing that the `seq[CigarElement]` does not get garbage-collected while the cigar is still in use because it is using a pointer underneath.

**Comment by andreas-wilm** [comment]
Thanks a lot Brent!
